# Generated by Django 4.0.2 on 2022-02-03 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('f_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('sti', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('BP', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('cancer', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('liver', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('heart', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('preggo', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('nausea', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('clot', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('want_baby', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('breastfeeding', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preggo', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('nausea', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('clot', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('want_baby', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('breastfeeding', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
