# Generated by Django 4.0 on 2022-01-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('sti', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('BP', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('cancer', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('liver', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('heart', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('preggo', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('nausea', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('clot', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('want_baby', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('breastfeeding', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preggo', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('nausea', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('clot', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('want_baby', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('breastfeeding', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('NOT', 'NOT SURE')], max_length=30, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
